version: '3.8'

services:
  app:
    build:
      context: .
    image: user-domain:v1.0
    container_name: userDomain
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true

volumes:
  mysql_data: